image: maven:latest

variables:
    GIT_SSL_NO_VERIFY: "true"
    
stages:
    - build
    - test
    
build:
    stage: build
    script:
     - mvn --settings settings.xml clean package -Dquarkus.container-image.build=true
