image: maven:latest

variables:
    GIT_SSL_NO_VERIFY: "true"
    
stages:
    - build
    - test
    
job 0:
    stage: build
    script:
     - mvn --settings settings.xml compile

job 1:
    stage: test