image: maven:latest

variables:
    GIT_SSL_NO_VERIFY: "true"
    
stages:
    - build
    - test
    
job1:
    stage: build
    script:
     - mvn --settings settings.xml compile

job2:
    stage: test